Feature/implement mayo estimator
Crypto-TII/CryptographicEstimators pull request #139
Opened 2024-05-01 20:20 UTC by fmerino21

### Description
- Basic structure for MAYOEstimator with parameters n (number of variables), m (number of polynomials), o (dimension of the oil space), k (whipping parameter) and q (order of the finite field). 
- Direct attack implementation with time and memory complexities. 
- The direct attack implementation uses `booleansolve_fxl` to find the optimal parameter `K` from the Furue, Nakamura and Takagi strategy. Then, it gets the time and memory complexities from the fastest algorithm to solve an instance of the MQ problem with $m' = m - \frac{kn - K}{m - K} + 1$ equations and $n'  = m' - K$ variables.  

### Review process
- Review the optimization process for the `K` parameter (function `_optimize_k` in `mayo_helper.py`).
- Review the time and memory complexities in the direct attack implementation. 

### Pre-approval checklist
- [ ] The code builds clean without any errors or warnings
- [ ] I've added/updated tests
- [ ] I've added/updated documentation if needed

2024-05-08 05:52 UTC, fmerino21 commented on cryptographic_estimators/MAYOEstimator/MAYOAlgorithms/direct_attack.py
> +    - ``w`` -- linear algebra constant (default: 2)
In this case the value actually comes from the `MAYOAlgorithm` class, where the value is 2.81 by default, is that ok ?

2024-05-08 05:52 UTC, fmerino21 commented on cryptographic_estimators/MAYOEstimator/MAYOAlgorithms/direct_attack.py
> +    - ``complexity_type`` -- complexity type to consider (0: estimate, 1: tilde O complexity, default: 0)
As both problems and schemes uses the same method to generate the table and considering that we will implement tilde O complexities in the future, I just force the `complexity_type` parameter to be 0 in the `MAYOAlgorithm` class but the user can still use the parameter show_tilde_o_times=1 when using `.table()` method

2024-05-17 08:44 UTC, Memphisd requested changes

2024-05-20 05:34 UTC, Javierverbel requested changes
Please add one test per row in Table5.1: of the MAYO specs

2024-05-20 05:34 UTC, Javierverbel commented on cryptographic_estimators/MAYOEstimator/mayo_estimator.py
> +            sage: E = MAYOEstimator(n=64, m=60, o=10, k=21, q=16)
Could you add one test per MAYO parameter set? Meaning that one, test for MAYO1, MAYO2, MAYO3 and  MAYO5?

Maybe we can remove some of the long test below.
Please add the tag  `# long time` for test taking more than  5-10 few seconds.

2024-05-20 13:12 UTC, Javierverbel submitted a review, later dismissed

2024-05-21 09:59 UTC, Javierverbel approved these changes

2024-05-22 11:24 UTC, Memphisd approved these changes
looks good to me

2024-05-27 10:42 UTC, merged