Fix/remove undesirable pytest prints
Crypto-TII/CryptographicEstimators pull request #153
Opened 2024-05-27 06:51 UTC by Dioprz

### Description
- Remove all the debugging prints that ended up in the pytest tests code, and made the output very hard to read.
- I also made small refactor to improve the style of the code.

### Review process
- You can switch to this branch and execute `make docker-pytest` to see the new cleaner output.

### Pre-approval checklist
- [x] The code builds clean without any errors or warnings
- [x] I've added/updated tests
- [x] I've added/updated documentation if needed

2024-05-31 04:22 UTC, Javierverbel approved these changes

2024-05-31 05:54 UTC, Javierverbel requested changes
While running `make docker-pytest` prints still appear.

2024-05-31 08:18 UTC, Dioprz commented
Being in the branch, can you try to execute this please?

```shell
make stop-container-and-remove container_name="pytest-estimators"
make docker-pytest
```

At my side everything is working as expected and I'm getting just some warnings.

2024-06-04 13:35 UTC, FloydZ submitted a review, later dismissed

2024-06-05 07:34 UTC, Javierverbel approved these changes

2024-06-05 09:23 UTC, merged