Refactor/python docstrings for regsd estimator
Crypto-TII/CryptographicEstimators pull request #191
Opened 2024-09-28 08:06 UTC by Dioprz

### Description

Implementation of https://github.com/Crypto-TII/CryptographicEstimators/pull/169 for RegSDEstimator.

### Review process

- A quick glance at the new docstrings would be great.
- Please search by FIX and TODO in the diff view, in case I has moved some previously existent comment.

**Estimator-specific doctests**
```shell
make docker-run
pytest --doctest-modules -n auto -vv cryptographic_estimators/RegSDEstimator
```

**Cumulative test (with all the already migrated docstrings)**
```shell
make docker-pytest-doctests
```

### Pre-approval checklist
- [x] The code builds clean without any errors or warnings
- [x] I've added/updated tests
- [x] I've added/updated documentation if needed

2024-09-30 08:30 UTC, FloydZ requested changes
Looks good to me. But I checked the new generated documentation. And it does not look correct.

![Screenshot_20240930_102834](https://github.com/user-attachments/assets/1dfbe0f3-a783-4ee0-8f6e-7fc300e43dec)

2024-10-07 05:52 UTC, Dioprz commented on cryptographic_estimators/RegSDEstimator/RegSDAlgorithms/regisd_enum.py
> +    #TODO: Update examples
Applied

2024-10-07 05:52 UTC, Dioprz commented on cryptographic_estimators/RegSDEstimator/RegSDAlgorithms/regisd_enum.py
> +    #TODO: Update examples
Done

2024-10-07 06:06 UTC, Dioprz commented
Look at how are generated the docstrings now:

![image](https://github.com/user-attachments/assets/66548284-97d2-4a64-b426-ba25a4eabe85)

Test with `make docker-doc`

All the required changes for this were added at https://github.com/Crypto-TII/CryptographicEstimators/pull/191/commits/932828b87e3e2f6ec3fc26733590573bae9b02a3.

Basically I made two changes:
- Include the Napoleon extension.
- I created a custom Sphinx extension able to parse the `**kwargs` parameter, as I used this pattern in all the new docstrings-related PRs (IIRC). Now they look pretty much the same as in the docstrings:

```python
    def __init__(self, n: int, k: int, w: int, memory_bound=inf, **kwargs):
        """Construct an instance of RegSDEstimator.

        Args:
            n (int): Code length.
            k (int): Code dimension.
            w (int): Error weight.
            memory_bound: Memory bound.
            **kwargs: Additional keyword arguments.
                excluded_algorithms: A list/tuple of excluded algorithms (default: None).
                nsolutions: No. of solutions.
        """
```

If you prefer to have this changes in another PR, let me know.

**Help required**

As you can see, I put the `kwargs_formatter.py` directly in the root of the project. I don't know if you prefer to create another directory, or put it directly into the `scripts/` or `docs/` directory so... Just tell me where you want it and I will apply the change. @FloydZ @Javierverbel

2024-10-07 09:33 UTC, Javierverbel approved these changes

2024-10-07 11:37 UTC, FloydZ approved these changes
Looks good. We delete all docs, and the final PR adds the newly generated docs then?

2024-10-07 13:05 UTC, merged

2024-10-07 13:05 UTC, Javierverbel commented
yes.